//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shoping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address_View
    {
        public int Add_id { get; set; }
        public string Address_line1 { get; set; }
        public Nullable<long> Alt_Mobile { get; set; }
        public long Mobile { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
        public string PIN { get; set; }
        public string State { get; set; }
        public string Dist { get; set; }
        public string City { get; set; }
        public string Add_Type { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public int u_id { get; set; }
        public string cart_statu { get; set; }
        public int Expr1 { get; set; }
    }
}
