//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shoping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancel_Order
    {
        public int cancel_id { get; set; }
        public int U_id { get; set; }
        public int od_id { get; set; }
        public string cancel_reason { get; set; }
        public System.DateTime cancel_dt { get; set; }
        public string cancel_status { get; set; }
    
        public virtual Order_Details Order_Details { get; set; }
        public virtual user_mst user_mst { get; set; }
    }
}
