//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shoping.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineShopping : DbContext
    {
        public OnlineShopping()
            : base("name=OnlineShopping")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<my_cart> my_cart { get; set; }
        public virtual DbSet<product_mst> product_mst { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User_Address> User_Address { get; set; }
        public virtual DbSet<user_mst> user_mst { get; set; }
        public virtual DbSet<Address_View> Address_View { get; set; }
        public virtual DbSet<MyCartView> MyCartViews { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Order_View> Order_View { get; set; }
        public virtual DbSet<Order_mst> Order_mst { get; set; }
        public virtual DbSet<Order_Details_View> Order_Details_View { get; set; }
        public virtual DbSet<Cancel_Order> Cancel_Order { get; set; }
    }
}
