//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shoping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class my_cart
    {
        public int cart_id { get; set; }
        public int u_id { get; set; }
        public int p_id { get; set; }
        public int quantity { get; set; }
        public double total_price { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public string cart_statu { get; set; }
    
        public virtual product_mst product_mst { get; set; }
        public virtual user_mst user_mst { get; set; }
    }
}
