//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shoping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyCartView
    {
        public int p_id { get; set; }
        public string p_name { get; set; }
        public double price { get; set; }
        public string p_desc { get; set; }
        public string image { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<double> rating { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> total_price { get; set; }
        public int u_id { get; set; }
        public string cart_statu { get; set; }
    }
}
