//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shoping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_mst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_mst()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int o_id { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<int> Add_id { get; set; }
        public Nullable<System.DateTime> order_dt { get; set; }
        public Nullable<double> total_amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual User_Address User_Address { get; set; }
        public virtual user_mst user_mst { get; set; }
    }
}
