//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shoping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_View
    {
        public Nullable<System.DateTime> order_dt { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> mrp { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<int> u_id { get; set; }
        public string p_name { get; set; }
        public string p_desc { get; set; }
        public Nullable<double> total_amount { get; set; }
        public string order_status { get; set; }
        public string image { get; set; }
        public double rating { get; set; }
        public int od_id { get; set; }
        public Nullable<int> o_id { get; set; }
        public Nullable<int> Add_id { get; set; }
        public string Address_line1 { get; set; }
        public string Add_Type { get; set; }
        public string City { get; set; }
        public string Dist { get; set; }
        public string State { get; set; }
        public string PIN { get; set; }
        public string Country { get; set; }
        public string Name { get; set; }
        public long Mobile { get; set; }
        public Nullable<long> Alt_Mobile { get; set; }
    }
}
