//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shoping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_Details()
        {
            this.Cancel_Order = new HashSet<Cancel_Order>();
        }
    
        public int od_id { get; set; }
        public Nullable<int> o_id { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> mrp { get; set; }
        public Nullable<double> discount { get; set; }
        public string order_status { get; set; }
        public Nullable<System.DateTime> action_dt { get; set; }
    
        public virtual product_mst product_mst { get; set; }
        public virtual Order_mst Order_mst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancel_Order> Cancel_Order { get; set; }
    }
}
