//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shoping.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class product_mst
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product_mst()
        {
            this.my_cart = new HashSet<my_cart>();
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int p_id { get; set; }
        public string p_name { get; set; }
        public double price { get; set; }
        public double CostPrice { get; set; }
        public string p_status { get; set; }
        public string p_desc { get; set; }
        public string image { get; set; }
        public HttpPostedFileBase File { get; set; }
        public int u_id { get; set; }
        public int c_id { get; set; }
        public int quantity { get; set; }
        public int discount { get; set; }
        public Nullable<System.DateTime> added_date { get; set; }
        public string brand { get; set; }
        public string img2 { get; set; }
        public string img3 { get; set; }
        public string img4 { get; set; }
        public string img5 { get; set; }
        public double rating { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<my_cart> my_cart { get; set; }
        public virtual user_mst user_mst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}
