//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Shoping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Address()
        {
            this.Order_mst = new HashSet<Order_mst>();
        }
    
        public int Add_id { get; set; }
        public int U_id { get; set; }
        public string Address_line1 { get; set; }
        public string Address_line2 { get; set; }
        public string Add_Type { get; set; }
        public string City { get; set; }
        public string Dist { get; set; }
        public string State { get; set; }
        public string PIN { get; set; }
        public string Country { get; set; }
        public string Name { get; set; }
        public long Mobile { get; set; }
        public Nullable<long> Alt_Mobile { get; set; }
    
        public virtual user_mst user_mst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_mst> Order_mst { get; set; }
    }
}
